name: my_dart_tool
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: "3.8.0"

# Add regular dependencies here.
dependencies:
  args: any
  path: any
  yaml: any

dev_dependencies:
  lints: any
  test: any