name: package_core
description: "A new Flutter package project."
homepage:
version: 0.0.1
publish_to: none

environment:
  sdk: 3.7.2
  flutter: 3.29.3

dependencies:
  flutter:
    sdk: flutter

  intl: any
  collection: any #array, List method
  dartz: any
  connectivity_plus: any
  flutter_dotenv: any
  get_it: any
  easy_localization: any
  upgrader: any
  web_socket_channel: any
  # Widget
  #
  flutter_core_datz:
    git:
      url: https://github.com/phatdat-dev/flutter_core_datz
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  flutter_gen_runner: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  assets:
    outputs:
      package_parameter_enabled: true # <- Add this line.
      class_name: AssetsCore

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - .env
    - assets/images/logo/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
